import pickle
def new(train_data):        
    s=''
    for i in range(len(train_data)):
        train_data[i]=np.array(train_data[i])
        train_data[i]=train_data[i].reshape(1,28,28,1)
        result=loaded_model.predict_classes(train_data[i])
        if(result[0]==10):
            s=s+'-'
        if(result[0]==11):
            s=s+'+'
        if(result[0]==12):
            s=s+'*'
        if(result[0]==0):
            s=s+'0'
        if(result[0]==1):
            s=s+'1'
        if(result[0]==2):
            s=s+'2'
        if(result[0]==3):
            s=s+'3'
        if(result[0]==4):
            s=s+'4'
        if(result[0]==5):
            s=s+'5'
        if(result[0]==6):
            s=s+'6'
        if(result[0]==7):
            s=s+'7'
        if(result[0]==8):
            s=s+'8'
        if(result[0]==9):
            s=s+'9'
        if(result[0]==13):
            s=s+'A'
        if(result[0]==14):
            s=s+'B'
        if(result[0]==15):
            s=s+'C'
        if(result[0]==16):
            s=s+'D'
        if(result[0]==17):
            s=s+'E'
        if(result[0]==18):
            s=s+'F'
        if(result[0]==19):
            s=s+'G'
        if(result[0]==20):
            s=s+'H'
        if(result[0]==21):
            s=s+'I'
        if(result[0]==22):
            s=s+'J'
        if(result[0]==23):
            s=s+'K'
        if(result[0]==24):
            s=s+'L'
        if(result[0]==25):
            s=s+'M'
        if(result[0]==26):
            s=s+'N'
        if(result[0]==27):
            s=s+'O'
        if(result[0]==28):
            s=s+'P'
        if(result[0]==29):
            s=s+'Q'
        if(result[0]==30):
            s=s+'R'
        if(result[0]==31):
            s=s+'S'
        if(result[0]==32):
            s=s+'T'
        if(result[0]==33):
            s=s+'U'
        if(result[0]==34):
            s=s+'V'
        if(result[0]==35):
            s=s+'W'
        if(result[0]==36):
            s=s+'X'
        if(result[0]==37):
            s=s+'Y'
        if(result[0]==38):
            s=s+'Z'
    return s

pickle_out = open("dict.pickle","wb")
pickle.dump(new, pickle_out)
pickle_out.close()